Ext.define('Xolens.module.enquiry.rsc.Column', {
    singleton: true,

    name: { text: 'Name', dataIndex: 'name', minWidth: 200, flex:1 },
    description: { text: 'Description', dataIndex: 'description', minWidth: 200,  },
    type: { text: 'Type', dataIndex: 'type', minWidth: 200,  },
    displaytext: { text: 'DisplayText', dataIndex: 'display_text', minWidth: 200,  },
    required: { text: 'Required', dataIndex: 'required', minWidth: 200,  },
    valuelist: { text: 'ValueList', dataIndex: 'value_list', minWidth: 200,  },
    group:{ text: 'Informations group' ,columns:[{ text: 'Name', dataIndex: 'group_name', minWidth: 200},]},
    maxrecords: { text: 'MaxRecords', dataIndex: 'max_records', minWidth: 200,  },
    field:{ text: 'Informations field' ,columns:[{ text: 'Name', dataIndex: 'field_name', minWidth: 200},]},
    title: { text: 'Title', dataIndex: 'title', minWidth: 200, flex:1 },
    form:{ text: 'Informations form' ,columns:[{ text: 'Name', dataIndex: 'form_name', minWidth: 200},]},
    sectionfield:{ text: 'Informations section field' ,columns:[]},
    position: { text: 'Position', dataIndex: 'position', minWidth: 200,  },
    section:{ text: 'Informations section' ,columns:[{ text: 'Name', dataIndex: 'section_name', minWidth: 200},]},
    participant:{ text: 'Informations participant' ,columns:[{ text: 'Name', dataIndex: 'participant_name', minWidth: 200},]},
    enquiry:{ text: 'Informations enquiry' ,columns:[{ text: 'Name', dataIndex: 'enquiry_name', minWidth: 200},{ text: 'Title', dataIndex: 'enquiry_title', minWidth: 200},]},
    state: { text: 'State', dataIndex: 'state', minWidth: 200,  },
    createtime: { text: 'CreateTime', dataIndex: 'create_time', minWidth: 200,  },
    updatetime: { text: 'UpdateTime', dataIndex: 'update_time', minWidth: 200,  },
    validationtime: { text: 'ValidationTime', dataIndex: 'validation_time', minWidth: 200,  },
    tablefield:{ text: 'Informations table field' ,columns:[{ text: 'Name', dataIndex: 'table_field_name', minWidth: 200},]},
})

