Ext.define('Xolens.module.enquiry.rsc.Content', {
    singleton: true,
    require: [
        'Xolens.module.enquiry.rsc.Api',
        'Xolens.module.enquiry.rsc.Form',
        'Xolens.module.enquiry.rsc.Detail',
    ],

    field: {
        paging: true,
        searchtool: true,
        title: "Gestion des fields",
        subtitle: "FIELDS",
        iconCls: 'x-fa fa-send',
        storeUrl: Xolens.module.enquiry.rsc.Api.field.storeUrl,
        deleteUrl: Xolens.module.enquiry.rsc.Api.field.deleteUrl,
        form: Xolens.module.enquiry.rsc.Form.field,
        detail: Xolens.module.enquiry.rsc.Detail.field,
        columns: ['name', 'type', 'displaytext', 'required', 'valuelist', 'description', 'editAction', 'deleteAction'],
        buttons: ['deletebtn', 'updatebtn', 'exportmenu', 'addbtn', 'plusmenu'],
        dialogs: [],
        extraConfig: {}
    },
    section: {
        paging: true,
        searchtool: true,
        title: "Gestion des sections",
        subtitle: "SECTIONS",
        iconCls: 'x-fa fa-send',
        storeUrl: Xolens.module.enquiry.rsc.Api.section.storeUrl,
        deleteUrl: Xolens.module.enquiry.rsc.Api.section.deleteUrl,
        form: Xolens.module.enquiry.rsc.Form.section,
        detail: Xolens.module.enquiry.rsc.Detail.section,
        columns: ['name', 'description', 'editAction', 'deleteAction'],
        buttons: ['deletebtn', 'updatebtn', 'exportmenu', 'addbtn', 'plusmenu'],
        dialogs: [],
        extraConfig: {}
    },
    form: {
        paging: true,
        searchtool: true,
        title: "Gestion des forms",
        subtitle: "FORMS",
        iconCls: 'x-fa fa-send',
        storeUrl: Xolens.module.enquiry.rsc.Api.form.storeUrl,
        deleteUrl: Xolens.module.enquiry.rsc.Api.form.deleteUrl,
        form: Xolens.module.enquiry.rsc.Form.form,
        detail: Xolens.module.enquiry.rsc.Detail.form,
        columns: ['name', 'description', 'primarysection', 'editAction', 'deleteAction'],
        buttons: ['deletebtn', 'updatebtn', 'exportmenu', 'addbtn', 'plusmenu'],
        dialogs: [],
        extraConfig: {}
    },
    tablefield: {
        paging: true,
        searchtool: true,
        title: "Gestion des tablefields",
        subtitle: "TABLEFIELDS",
        iconCls: 'x-fa fa-send',
        storeUrl: Xolens.module.enquiry.rsc.Api.tablefield.storeUrl,
        deleteUrl: Xolens.module.enquiry.rsc.Api.tablefield.deleteUrl,
        form: Xolens.module.enquiry.rsc.Form.tablefield,
        detail: Xolens.module.enquiry.rsc.Detail.tablefield,
        columns: ['name', 'maxrecords', 'description', 'field', 'editAction', 'deleteAction'],
        buttons: ['deletebtn', 'updatebtn', 'exportmenu', 'addbtn', 'plusmenu'],
        dialogs: [],
        extraConfig: {}
    },
    enquiry: {
        paging: true,
        searchtool: true,
        title: "Gestion des enquirys",
        subtitle: "ENQUIRYS",
        iconCls: 'x-fa fa-send',
        storeUrl: Xolens.module.enquiry.rsc.Api.enquiry.storeUrl,
        deleteUrl: Xolens.module.enquiry.rsc.Api.enquiry.deleteUrl,
        form: Xolens.module.enquiry.rsc.Form.enquiry,
        detail: Xolens.module.enquiry.rsc.Detail.enquiry,
        columns: ['name', 'title', 'description', 'form', 'editAction', 'deleteAction'],
        buttons: ['deletebtn', 'updatebtn', 'exportmenu', 'addbtn', 'plusmenu', 'enqueryImport'],
        dialogs: [],
        extraConfig: {}
    },
    formsection: {
        paging: true,
        searchtool: true,
        title: "Gestion des formsections",
        subtitle: "FORMSECTIONS",
        iconCls: 'x-fa fa-send',
        storeUrl: Xolens.module.enquiry.rsc.Api.formsection.storeUrl,
        deleteUrl: Xolens.module.enquiry.rsc.Api.formsection.deleteUrl,
        form: Xolens.module.enquiry.rsc.Form.formsection,
        detail: Xolens.module.enquiry.rsc.Detail.formsection,
        columns: ['position', 'section', 'form', 'editAction', 'deleteAction'],
        buttons: ['deletebtn', 'updatebtn', 'exportmenu', 'addbtn', 'plusmenu'],
        dialogs: [],
        extraConfig: {}
    },
    tablecolumn: {
        paging: true,
        searchtool: true,
        title: "Gestion des tablecolumns",
        subtitle: "TABLECOLUMNS",
        iconCls: 'x-fa fa-send',
        storeUrl: Xolens.module.enquiry.rsc.Api.tablecolumn.storeUrl,
        deleteUrl: Xolens.module.enquiry.rsc.Api.tablecolumn.deleteUrl,
        form: Xolens.module.enquiry.rsc.Form.tablecolumn,
        detail: Xolens.module.enquiry.rsc.Detail.tablecolumn,
        columns: ['position', 'tablefield', 'field', 'editAction', 'deleteAction'],
        buttons: ['deletebtn', 'updatebtn', 'exportmenu', 'addbtn', 'plusmenu'],
        dialogs: [],
        extraConfig: {}
    },
    sectionfield: {
        paging: true,
        searchtool: true,
        title: "Gestion des sectionfields",
        subtitle: "SECTIONFIELDS",
        iconCls: 'x-fa fa-send',
        storeUrl: Xolens.module.enquiry.rsc.Api.sectionfield.storeUrl,
        deleteUrl: Xolens.module.enquiry.rsc.Api.sectionfield.deleteUrl,
        form: Xolens.module.enquiry.rsc.Form.sectionfield,
        detail: Xolens.module.enquiry.rsc.Detail.sectionfield,
        columns: ['position', 'field', 'section', 'editAction', 'deleteAction'],
        buttons: ['deletebtn', 'updatebtn', 'exportmenu', 'addbtn', 'plusmenu'],
        dialogs: [],
        extraConfig: {}
    },
    fieldvalue: {
        paging: true,
        searchtool: true,
        title: "Gestion des fieldvalues",
        subtitle: "FIELDVALUES",
        iconCls: 'x-fa fa-send',
        storeUrl: Xolens.module.enquiry.rsc.Api.fieldvalue.storeUrl,
        deleteUrl: Xolens.module.enquiry.rsc.Api.fieldvalue.deleteUrl,
        form: Xolens.module.enquiry.rsc.Form.fieldvalue,
        detail: Xolens.module.enquiry.rsc.Detail.fieldvalue,
        columns: ['sectionfield', 'enquiry', 'value', 'editAction', 'deleteAction'],
        buttons: ['deletebtn', 'updatebtn', 'exportmenu', 'addbtn', 'plusmenu'],
        dialogs: [],
        extraConfig: {}
    },
})